### ISSUE TITLE
terraform plan/apply: Error: failed to execute "bash"

### ISSUE THREAD

**Issue by harrygreen** [dealmore/terraform-aws-next-js#103]
I'm getting this while executing `terraform plan` or `terraform apply`:

```shell
$ terraform plan

Error: failed to execute "bash": .terraform/modules/tf_next.next_image.lambda_content/download.sh: line 7: wget: command not found
Failed to download https://cdn.jsdelivr.net/npm/@dealmore/tf-next-image-optimization@10.0.5-beta2/dist.zip

Error: failed to execute "bash": .terraform/modules/tf_next.statics_deploy.lambda_content/download.sh: line 7: wget: command not found
Failed to download https://cdn.jsdelivr.net/npm/@dealmore/terraform-next-deploy-trigger@0.2.0/dist.zip

Error: failed to execute "bash": .terraform/modules/tf_next.proxy.proxy_package/download.sh: line 7: wget: command not found
Failed to download https://cdn.jsdelivr.net/npm/@dealmore/terraform-next-proxy@0.5.0/dist.zip
```

The referenced zips appear to be fine when accessing via HTTP.

`tf-next build` and `terraform init` completed with no issues.

Any ideas?

--
Node 14.16
macOS 11.2.3

**Comment by ofhouse** [comment]
Hi, when running `terraform apply` we currently rely on some bash scripts that are executed while running the command.
One of the bash commands uses the program `wget` to download components for some Lambda related workflows (e.g. Proxy, Image optimization, etc).

You should make sure that `wget` is installed and available in your Terminal:
```
wget --version 
```

If it is not installed, you need to install it first (e.g. with [Homebrew](https://stackoverflow.com/a/17094214/831465)).
Sorry for the confusion here, I will try to add some more information what programs should be installed in addition to Terraform soon (Most of them are already preinstalled with most OS, but depending on the configuration there can be differences).

**Comment by harrygreen** [comment]
Danke @ofhouse, that solved it!  `wget` wasn't installed. I guess I was expecting `bash: wget: command not found`.

Don't apologise - this is a great project. Thanks.
