### ISSUE TITLE
Lambda Permission

### ISSUE THREAD

**Issue by ahmed-rezk-dev** [dealmore/terraform-aws-next-js#114]
Hey guys. I just download the example repo and run it after setting up AWS keys. I'm getting this error at the end 

`Error: Error adding new Lambda Permission for __NEXT_API_LAMBDA_0-9fc65033: ResourceNotFoundException: Function not found: arn:aws:lambda:us-west-2:880733008175:function:__NEXT_API_LAMBDA_0-9fc65033
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: "65342f79-69fc-4fa5-a58f-44bd79c40d8c"
  },
  Message_: "Function not found: arn:aws:lambda:us-west-2:880733008175:function:__NEXT_API_LAMBDA_0-9fc65033",
  Type: "User"
}

  on .terraform/modules/tf_next/main.tf line 82, in resource "aws_lambda_permission" "current_version_triggers":
  82: resource "aws_lambda_permission" "current_version_triggers" {`

**Comment by ofhouse** [comment]
Can you specify which example you have used, was it the [complete example](https://github.com/dealmore/terraform-aws-next-js/tree/main/examples/complete)?

I could not reproduce the issue locally, could you provide more steps for reproduction, like in this example: https://github.com/dealmore/terraform-aws-next-js/issues/100#issuecomment-817307279
