### ISSUE TITLE
Default root object not being set on s3 cloudfront distribution

### ISSUE THREAD

**Issue by jamesla** [dealmore/terraform-aws-next-js#13]
This doesn't set the default root object in cloud front which means that everything 404's unless you manually specify `/index` after the url.

This can be fixed by manually adding a default_root_object path of index in cloudfront once it has been deployed.

Ideally `default_root_object = "index"` should be configured on the cloudfront distribution here:

https://github.com/dealmore/terraform-aws-next-js/blob/2d88ce0fb9f93ff49eb43570d6d455e2a1a3ff2e/modules/proxy/main.tf#L62

**Comment by ofhouse** [comment]
Hi,
thanks for raising this issue.

That is indeed not the desired behaviour here.
We currently use the module mostly together with SSR lambdas to handle the index routes so we did not notice the wrong behaviour on static deployments here.

I'll take a look soon and update the package 👍

**Comment by ofhouse** [comment]
This is now fixed in the [v0.1.2](https://github.com/dealmore/terraform-aws-next-js/releases/tag/v0.1.2) release.
I also added a new static example to ensure that static deployments are better tested in the future.
