### ISSUE TITLE
cloudfront_origins and cloudfront_custom_behaviors configuration

### ISSUE THREAD

**Issue by hypermurea** [dealmore/terraform-aws-next-js#133]
I tried to configure cloudfront_origins to route certain requests but I was unable to figure out the correct syntax for this: in the code it seems the origins defined in this module are joined to cloudfront_origins with concat(), but the objects are not exactly the same resulting in the error:

```
 proxy_cloudfront_origins = var.cloudfront_origins != null ? concat(
 174:     local.next_image_cloudfront_origins,
 175:     var.cloudfront_origins
 176:   ) : local.next_image_cloudfront_origins
    |----------------
    | local.next_image_cloudfront_origins is list of object with 1 element
    | var.cloudfront_origins is list of object with 1 element
```

I assume this is because cloudfront_origins does not match the format in which next_image_cloudfront_origins is defined. My origin configurations are pretty simple and I wonder is there a specific format I can match to in order to make this work? 

I assume the same issue might be involved with cloudfront_custom_behaviors. 

Any help greatly appreciated, thanks!

**Comment by ofhouse** [comment]
Hi, yep the documentation on this is a bit limited for now.
But since we will provide a better solution for this scenario in #55 I don't saw the need to provide further documentation on this topic.

However here is an example how we use `cloudfront_origins` and `cloudfront_custom_behaviors` internally:

```
module "next_js" {
  source  = "dealmore/next-js/aws"

  ...

  cloudfront_origins = [
    {
      domain_name = "example.com"
      origin_id   = "my origin"

      custom_origin_config = {
        http_port              = 80
        https_port             = 443
        origin_protocol_policy = "https-only"
        origin_ssl_protocols   = ["TLSv1.2"]
      }
    }
  ]
  cloudfront_custom_behaviors = [
    {
      path_pattern     = "/my-path"
      allowed_methods  = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
      cached_methods   = ["GET", "HEAD", "OPTIONS"]
      target_origin_id = "my origin"

      forwarded_values = {
        query_string = false

        cookies = {
          forward = "all"
        }
      }

      min_ttl                = 0
      default_ttl            = 86400
      max_ttl                = 31536000
      compress               = false
      viewer_protocol_policy = "redirect-to-https"
    }
  ]
}
```

`cloudfront_origins` and `cloudfront_custom_behaviors` both require an array of objects.

**Comment by hypermurea** [comment]
Thanks for the example. I tried with this test configuration and I can manage to get cloudfront_origins working but cloudfront_custom_behaviors seems to be very difficult to get to work as the keys must match verbatim to what is specified in the internal custom behaviors. Seems like a big improvement if a new release allows using an external cloudfront config with your module 👍  I'll wait or fork your project if needed, thanks!
