### ISSUE TITLE
Responsive images not being generated

### ISSUE THREAD

**Issue by dottodot** [dealmore/terraform-aws-next-js#142]
I had this issue in my test app but have also tried using your example just to make sure, but the image component isn't generating the various image sizes. Even though the width query param is present the original image size is always returned.

I've also noticed that `_next/image` has not been created in the bucket.

**Comment by ofhouse** [comment]
Yes, we had an issue in the image optimizer that prevented the optimization to work properly: https://github.com/dealmore/terraform-aws-next-js-image-optimization/pull/44

It's already fixed. But we released it as major version [v11.0.0](https://github.com/dealmore/terraform-aws-next-js-image-optimization/releases/tag/v11.0.0) and therefore the version constraint (`~> 10.0.8`) in the main.tf does not allow to upgrade to the latest version:
https://github.com/dealmore/terraform-aws-next-js/blob/dd5b61321e9b2bf3e8b56e418ae3700e812007f3/main.tf#L153-L157 

I will publish a new release soon that increases the version constraint, which should fix the issue.

The image optimizer does not use a S3 bucket to store the processed images, instead the images are stored in CloudFront Origin Shield (which provides a similar caching behavior).
For more information see the repository of the image optimization module: https://github.com/dealmore/terraform-aws-next-js-image-optimization

Again thanks for reporting!

**Comment by ofhouse** [comment]
This is now fixed in the [v0.9.1 release](https://github.com/dealmore/terraform-aws-next-js/releases/tag/v0.9.1).
