### ISSUE TITLE
terraform plan/apply - Error: can't find external program "bash"

### ISSUE THREAD

**Issue by rodrigogazzaneo** [dealmore/terraform-aws-next-js#148]
Hello,
I tried installing wget but i didn't work. If you could help me, I would be gratefull.

Error: can't find external program "bash"
│
│   with module.next-js_example_complete.module.tf_next.module.next_image[0].module.lambda_content.data.external.download[0],
│   on .terraform\modules\next-js_example_complete.tf_next.next_image.lambda_content\main.tf line 32, in data "external" "download":
│   32: data "external" "download" {
│
╵
╷
│ Error: can't find external program "bash"
│
│   with module.next-js_example_complete.module.tf_next.module.proxy.module.proxy_package.data.external.download[0],
│   on .terraform\modules\next-js_example_complete.tf_next.proxy.proxy_package\main.tf line 32, in data "external" "download":
│   32: data "external" "download" {
│
╵
╷
│ Error: can't find external program "bash"
│
│   with module.next-js_example_complete.module.tf_next.module.statics_deploy.module.lambda_content.data.external.download[0],
│   on .terraform\modules\next-js_example_complete.tf_next.statics_deploy.lambda_content\main.tf line 32, in data "external" "download":
│   32: data "external" "download" {
│
╵
╷
│ Error: can't find external program "bash"
│
│   with module.tf_next.module.next_image[0].module.lambda_content.data.external.download[0],
│   on .terraform\modules\tf_next.next_image.lambda_content\main.tf line 32, in data "external" "download":
│   32: data "external" "download" {
│
╵
╷
│ Error: can't find external program "bash"
│
│   with module.tf_next.module.proxy.module.proxy_package.data.external.download[0],
│   on .terraform\modules\tf_next.proxy.proxy_package\main.tf line 32, in data "external" "download":
│   32: data "external" "download" {
│
╵
╷
│ Error: can't find external program "bash"
│
│   with module.tf_next.module.statics_deploy.module.lambda_content.data.external.download[0],
│   on .terraform\modules\tf_next.statics_deploy.lambda_content\main.tf line 32, in data "external" "download":
│   32: data "external" "download" {

**Comment by ofhouse** [comment]
Hi,

it looks like you are try to run it on a Windows machine.
Windows is currently not supported since we internally rely on a Bash script that is executed during `terraform apply`.

Your options here are:
- Use the [Linux subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
- Use [Terraform Cloud](https://www.terraform.io/cloud)

Which we could get rid of this Bash script, since it is the only thing that blocks cross-platform usage and causes many other problems, but unfortunately there is currently no other solution.

**Comment by ofhouse** [comment]
Oh, forgot to mention there is a third option:

You can install the [AWS CLI](https://aws.amazon.com/cli/) and then set the `use_awscli_for_static_upload` attribute, which then uses the AWS CLI to perform the task that previously needed Bash and wGet.

```diff
...

module "tf_next" {
  source = "dealmore/next-js/aws"

+ use_awscli_for_static_upload = true

  providers = {
    aws.global_region = aws.global_region
  }
}

```

Not tested, but this should work on Windows.

**Comment by rodrigogazzaneo** [comment]
> Oh, forgot to mention there is a third option:
> 
> You can install the [AWS CLI](https://aws.amazon.com/cli/) and then set the `use_awscli_for_static_upload` attribute, which then uses the AWS CLI to perform the task that previously needed Bash and wGet.
> 
> ```diff
> ...
> 
> module "tf_next" {
>   source = "dealmore/next-js/aws"
> 
> + use_awscli_for_static_upload = true
> 
>   providers = {
>     aws.global_region = aws.global_region
>   }
> }
> ```
> 
> Not tested, but this should work on Windows.

It didn't work on windows, but to be honest didn't spend much time on it. I launched an Linux Ubuntu Ec2 and it worked fine.
Thank you !!

**Comment by rodrigogazzaneo** [comment]
I'll create a new issue if anyone can relate.

**Comment by ofhouse** [comment]
I'm going to close this issue because it has been inactive for 30 days ⏳. This helps to find and focus on the active issues.
