### ISSUE TITLE
error putting S3 Bucket Notification Configuration - status code: 400

### ISSUE THREAD

**Issue by rodrigogazzaneo** [dealmore/terraform-aws-next-js#150]
Hi,
I was able to do the terraform apply and the resources seem to be created, but I got an error in the end:

Error: error putting S3 Bucket Notification Configuration: InvalidArgument: Unable to validate the following destination configurations
│       status code: 400, request id: TATGME2XZWRP1FR3, host id: fnGdeSiFveVnHT0/hyjLLSw4fZYX4UWxC3H9PJcxQRzIddP2KFrQgYL/eCyTVTn11CxaTaDllK4=
│
│   with module.tf_next.module.statics_deploy.aws_s3_bucket_notification.on_create,
│   on .terraform/modules/tf_next/modules/statics-deploy/main.tf line 22, in resource "aws_s3_bucket_notification" "on_create":
│   22: resource "aws_s3_bucket_notification" "on_create" {

Do you know what's it about?

Best regards!

**Comment by ofhouse** [comment]
For reference (If someone finds it though search etc.): This is a duplicate of #138.
