### ISSUE TITLE
Doubled resources on deploy

### ISSUE THREAD

**Issue by rodrigogazzaneo** [dealmore/terraform-aws-next-js#152]
Hello,

I don't know if its on purpose or if I missed something. I've tried to look for it on the documentation but could not find anything.

When I builded and applied the terraform script, it generated 4 cloudfront distributions (it's the same for the rest of the structure):
2 tf-next - Main
2 tf-next - Proxy-Config

Is that normal? If not, any idea where I could fix it?

![image](https://user-images.githubusercontent.com/86314666/123457311-2bc69500-d5ba-11eb-9f14-f89d268c4874.png)

Best regards,
Rodrigo

**Comment by ofhouse** [comment]
Hi Rodrigo,

no, a single use of the module should only create 2 CloudFront distributions (1x Main, 1x Proxy-Config).
Without looking at your Terraform code it is very difficult to determine if there is an error, running the examples gives me the desired behavior.

You could try to set a unique `deployment_name` and then run `terraform apply` again to see which of the Terraform distributions are actually managed by your config:
```diff
module "tf_next" {
  source = "dealmore/next-js/aws"

+ deployment_name = "test-a"

  providers = {
    aws.global_region = aws.global_region
  }
}
```

The comments of the CloudFront distributions then should change to
```
test-a - Proxy-Config
test-a - Main
```

**Comment by rodrigogazzaneo** [comment]
Hi ofhouse,
See how is part of may main.tf

```
module "tf_next" {
  source = "dealmore/next-js/aws"
  use_awscli_for_static_upload = true
  deployment_name = "test-a"
  providers = {
    aws.global_region = aws.global_region
  }
}

module "next-js" {
  source  = "dealmore/next-js/aws"
  version = "0.9.1"
  use_awscli_for_static_upload = true
  deployment_name = "sun-front-v4"
  # insert the 4 required variables here
}

output "cloudfront_domain_name" {
  value = module.tf_next.cloudfront_domain_name
```

So I changed to test-a and sun-front-v4 to see how it would impact and that's the output:

![image](https://user-images.githubusercontent.com/86314666/123468276-ea3ce680-d5c7-11eb-98fe-5ccd9549b796.png)

No changes on the main but on the others.

I tried to run the main.tf without the tf_next but it doesn't work.

Sorry for maybe so many beginners questions, it's my first time managing terraform.

Thanks,
Rodrigo

**Comment by ofhouse** [comment]
You are basically creating 2 independent tf-next deployments here, since every use of

```tf
module "xxx" {
  source  = "dealmore/next-js/aws"

  ...
}
```

will create another stack (which includes the creation of 2 CloudFront instances, and all other resources).
You define `module "tf_next"` and `module "next-js"` which are two totally independent stacks with different names.

Not sure why the name of the main CloudFront distributions is not changed here, but removing one of the module definitions should result in a deletion of the 2 redundant distributions.

**Comment by rodrigogazzaneo** [comment]
I imagined so, but I tried changing the main.tf file to have only one of them and some errors appeared saying the module were not determined, etc.

I am destroying all the resources, I am changing de main.tf to just 1 deployment and I am running build an apply again.

I'll let you know if it works.

Thanks

**Comment by rodrigogazzaneo** [comment]
It worked great when building and applying again.
Thank you,

**Comment by ofhouse** [comment]
I'm going to close this issue because it has been inactive for 30 days ⏳. This helps to find and focus on the active issues.
