### ISSUE TITLE
Support for provisioned concurrency

### ISSUE THREAD

**Issue by jwstanly** [dealmore/terraform-aws-next-js#153]
Is there any way to provision concurrency for the Lambda@Edge routing proxy and the regional Next.js Lambdas? If I manually add provisioned concurrency configurations in the AWS Management Console, will the configs get overridden the next time I deploy my app?

**Comment by ofhouse** [comment]
Hi,

I thought about adding provisioned concurrency a few times, but in general I see no need in using it:
- It's [not supported](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions-restrictions.html#lambda-at-edge-runtime-restrictions) on Lambda@Edge
- It's pretty expensive
- We may change our approach how many regional Lambdas we generate (Currently it's mostly only one, but when #86 is implemented, this could be much more (1 per route, als Vercel also does)
- Cold start times of Lambdas are currently at [~ 200-400ms](https://mikhail.io/serverless/coldstarts/aws/)

What would be your use case for provisioned concurrency?

**Comment by jwstanly** [comment]
Thanks for reaching back out

The use case would simply be faster response times. This app's backend is also serverless (API Gateway + Lambda + Aurora). Response times vary from 0-10 seconds. I'm not sure whether Next.js or the backend is contributing more to cold start delays. Albeit pricy, I was considering provisioning since the Next.js Lambdas aren't per route, so there'd only be 1 to pay for. Looking for performance gains wherever possible.

Thanks for letting me know about Lambda@Edge not supporting provisioned concurrency, I was not aware of that. 

I'm still in research mode right now. I'm thinking about testing how provisioning different parts of the app impact response times, including Tf-Next. If I find anything meaningful, I'll be sure to share. (I've really enjoyed using this tool, thanks for everything)

**Comment by ofhouse** [comment]
I'm going to close this issue because it has been inactive for 30 days ⏳. This helps to find and focus on the active issues.
