### ISSUE TITLE
Expose module.proxy.lambda_edge_arn in tf_next outputs

### ISSUE THREAD

**Issue by curtis-trynow-io** [dealmore/terraform-aws-next-js#163]
It would be nice to add outputs into the outputs.tf for:

- target_origin_id
- lambda_arn

for tf_next so that it is then accessible for custom `ordered_cache_behavior` blocks in your own main.tf for customizing the CloudFront distro.  As an example use case, consider requests to `/api` that you do not want to cache at all.  I think the current recommendation would be to do something like this:

```
  ordered_cache_behavior {
    path_pattern = "/api/*"
    allowed_methods = ["GET", "HEAD", "OPTIONS", "PUT", "PATCH", "POST", "DELETE"]
    cached_methods = ["GET", "HEAD", "OPTIONS"]
    target_origin_id = "tf-next-s3-static-content" # must be hard-coded

    compress = false
    viewer_protocol_policy = "redirect-to-https"

    origin_request_policy_id = data.aws_cloudfront_origin_request_policy.all_viewer.id
    cache_policy_id = data.aws_cloudfront_cache_policy.caching_disabled.id

    lambda_function_association {
      event_type = "origin-request"
      lambda_arn = module.tf_next. ... # this is completely inaccessible
      include_body = false
    }
```

which is ugly and incomplete.  The alternative is to edit the `default_cache_behavior` to customize the policies there hwich is how I am currently going to do this, but I would rather not hack into TF Next's defaults.

**Comment by curtis-trynow-io** [comment]
I could also go at this using `dynamic` but that is also going to lead to some really hacked code that depends on TF Next not changing its underlying resources rather than exposing them for consumption.

**Comment by ofhouse** [comment]
You should be able to use the `cloudfront_default_cache_behavior` for this use-case.
A default cache behavior in CloudFront has the same properties as an ordered cache behavior besides the `path_pattern` property.

Not tested, but I think something like this should work:

```hcl
module "tf_next" {
  source = "dealmore/next-js/aws"
  ...
}

locals {
  # Create a new ordered cache behavior from the default cache behavior by adding the path_pattern property
  api_cache_behavior = merge(module.tf_next.cloudfront_default_cache_behavior, {
    path_pattern = "/api/*"
  })
}

resource "aws_cloudfront_distribution" "distribution" {
  ...

  dynamic "ordered_cache_behavior" {
    for_each = [local.api_cache_behavior]

    content {
      path_pattern     = ordered_cache_behavior.value["path_pattern"]
      allowed_methods  = ordered_cache_behavior.value["allowed_methods"]
      cached_methods   = ordered_cache_behavior.value["cached_methods"]
      target_origin_id = ordered_cache_behavior.value["target_origin_id"]

      compress               = ordered_cache_behavior.value["compress"]
      viewer_protocol_policy = ordered_cache_behavior.value["viewer_protocol_policy"]

      origin_request_policy_id = ordered_cache_behavior.value["origin_request_policy_id"]
      cache_policy_id          = ordered_cache_behavior.value["cache_policy_id"]
    }
  }
}
```

**Comment by curtis-trynow-io** [comment]
Ah, got it.  That's a really smart use of `merge()` with `locals` for overriding as the latter source of input for the merge.  I will give that shot.  Maybe this is worth putting in the docs somewhere in https://github.com/dealmore/terraform-aws-next-js/tree/main/examples/with-existing-cloudfront.  Thank you for the prompt reply!

**Comment by curtis-trynow-io** [comment]
I had to go one level deeper accessing the default behavior like:

```terraform
locals {
  api_cache_behavior = merge(module.tf_next.cloudfront_default_cache_behavior.default_behavior, {
    path_pattern = "/api/*"
    ...
  })
}
```

but then everything worked as suggested for merging in overrides.  I sincerely appreciate the recommendation and think this would be great to have in the docs.  Thank you!

**Comment by ofhouse** [comment]
Ah yes, forgot that we put the actual behavior in a sub-property so that it could directly consumed by a dynamic block. Glad you found out by yourself 👍

I really like the idea of adding common use cases from the issues to the docs.
Behind the scenes I already started working on a dedicated website for this project and I plan to put guides on it that cover advanced customization of the module.

This way we can ensure that the examples stay simple and understandable and can also provide resources for working with the module.

Stay tuned for more, happy I could help 😊
