### ISSUE TITLE
CloudFront - Alternate domain names

### ISSUE THREAD

**Issue by rodrigogazzaneo** [dealmore/terraform-aws-next-js#165]
Hi,
If I try to add only a cname or alias on Route53 it will not redirect properly to my CloudFront Domain. If I add an aliases and viewer_certificate info it works fine.
However I was not able to keep this changes in future "terraform applies". I tried changing the tfstate and inserted cloudfront_external_arn and cloudfront_external_id pointing to the created CF in main.tf, but it is always overwrited.

How is it possible to direct my domain to the cloudfront distribution and keep it automated in future deploys?

Thank you,
Rodrigo

**Comment by ofhouse** [comment]
Hi,
let me quickly recap the problem, to see if I understand the situation correctly:

1. You have a domain (`example.com`) and it's CNAME is pointing to the CloudFront distribution (`xyz.cloudfront.net`)
2. You want to redirect incoming requests to `example.com` to `xyz.cloudfront.net`
3. The domain `example.com` **is not added** as alias to the CloudFront distribution

From my understanding CloudFront will only accept incoming traffic from external domains when the alias is set correctly.

Without an code example it is very difficult to see why your setup is failing.
We created a [custom domain example](https://github.com/dealmore/terraform-aws-next-js/blob/main/examples/with-custom-domain/main.tf), that is tested and is working fine with external domains.
Could you tell where your setup is different from the example code?

**Comment by rodrigogazzaneo** [comment]
Hi,
That's exactly it. 

After following this example it worked fine. Thank you very much for your help.
