### ISSUE TITLE
Create own Next.js runtime

### ISSUE THREAD

**Issue by ofhouse** [dealmore/terraform-aws-next-js#36]
Since Vercel pulled the trigger and moved (https://github.com/vercel/vercel/pull/5640) their Next.js runtime into a private repository, we no longer have access to their builder and can use it in the future. 🙈

So we have to move on (like we already did with the bridge package) and develop our own runtime for doing this.

**Comment by lcswillems** [comment]
I am not sure to understand what `now-next` was responsible of? Building the code?

**Comment by ofhouse** [comment]
Yep, it's the secret sauce that Vercel uses to make Next.js runnable inside AWS Lambda.
It builds Next.js with a special serverless target and splits it into multiple chunks so that different routes can be served by different Lambdas.

**Comment by lcswillems** [comment]
Okay I see! And given the amount of lines of code that had been removed, I imagine this a huge work?

**Comment by ofhouse** [comment]
Not that big, since we can simply fork it and integrate it into this repository.

The hard work is to maintain the package and add support for upcoming Next.js features that are Vercel exclusive.
Currently Vercel has not dropped big changes, but I guess with the release of Next.js 11 they will also add some goodies that only work with Vercel in the first place (Like they did with static regeneration in 9 and internationalization in 10).

**Comment by lcswillems** [comment]
I see what you mean! Thank you for all these explanations!
