### ISSUE TITLE
Use with external CloudFront resource

### ISSUE THREAD

**Issue by ofhouse** [dealmore/terraform-aws-next-js#55]
Currently the main CloudFront resource is created & managed by the module itself.
While this is great as a quick setup for new users, it can become difficult for advanced use cases to integrate the module into an existing setup.

So we should switch to a similar approach as we did on the [image optimizer module](https://github.com/dealmore/terraform-aws-next-js-image-optimization):
- Create a managed CloudFront distribution by default (Quick setup)
- Prevent creation of CloudFront distribution and export all configuration (Cache & Origin Policies), so that it can be integrated into an existing CloudFront Distribution

## ToDo
- [ ] Rework Custom Domain Example to use external CloudFront distribution

**Comment by chamilad** [comment]
Thanks for introducing this feature! In my case I found that certain changes (ex: resource names) could recreate CF distribution and I have to update naming manually each time my pipeline runs. This decoupling helps to keep that constant.
