### ISSUE TITLE
Error: no matching Route53Zone found

### ISSUE THREAD

**Issue by underyx** [dealmore/terraform-aws-next-js#60]
Following the custom domain example, I get this error:

```
Error: no matching Route53Zone found

  on .terraform/modules/tf_next/main.tf line 240, in data "aws_route53_zone" "alias_domains":
 240: data "aws_route53_zone" "alias_domains" {
```

Note how this data block just picks up the first item from domain names, which is set to `domain_names      = [local.custom_domain]` in the example, and thus has no trailing dot. Could that be the issue? Although updating to ` domain_names      = ["${local.custom_domain}."]` does not fix it.

**Comment by underyx** [comment]
Managed to fix it with

```diff
 data "aws_route53_zone" "alias_domains" {
   count = var.create_domain_name_records ? length(var.domain_zone_names) : 0
 
-  name = var.domain_zone_names[count.index]
+  zone_id = var.domain_zone_names[count.index]
 }
```

and I'd submit a PR, but I can't figure out how to find this `.terraform/modules/tf_next/main.tf` file on GitHub 😕

**Comment by ofhouse** [comment]
Thanks for reporting, currently busy but will take a look by tomorrow 👍 

The `main.tf` can be found here:
 https://github.com/dealmore/terraform-aws-next-js/blob/7adffcf2e632a25bba14d4d394835da97c201f69/main.tf#L243

**Comment by underyx** [comment]
No worries, thanks for publishing this module!
