### ISSUE TITLE
feature request: Support rewriting to an external URL

### ISSUE THREAD

**Issue by underyx** [dealmore/terraform-aws-next-js#65]
Seems like this doesn't work at the moment: https://nextjs.org/docs/api-reference/next.config.js/rewrites#rewriting-to-an-external-url

**Comment by ofhouse** [comment]
Interesting, thought that this was already supported, but looking at the code I see that we always change the endpoint back to the internal API-Gateway route 🙈 

Anyway should be not a big deal since CloudFront should be able to handle such behaviour 👍
