### ISSUE TITLE
s3-put 400 bad request error

### ISSUE THREAD

**Issue by sprackle** [dealmore/terraform-aws-next-js#90]
Hi, I am getting the following error when running `terraform apply`:

`Error: Error running command './s3-put -r ca-central-1 -T /Users/a/Workspace/a/.next-tf/static-website-files.zip /next-tf-deploy-source20210329045608925600000002/static-website-files.zip': exit status 22. Output: unknown option '-mac'`

`curl: (22) The requested URL returned error: 400 Bad Request`

I am running on macOS Sierra.

Thanks!

**Comment by ofhouse** [comment]
Looks like your OpenSSL version is too old.
`-mac` option was introduced with OpenSSL 1.0.0 in 2010.

You can check the version by running the following command from your terminal:
```sh
openssl version
```

**Comment by ofhouse** [comment]
I'm going to close this issue because it has been inactive for 30 days ⏳. This helps to find and focus on the active issues.
