### ISSUE TITLE
Required target for deployment

### ISSUE THREAD

**Issue by otekdo** [dealmore/terraform-aws-next-js#96]
![image](https://user-images.githubusercontent.com/65221868/113094082-114d6d00-91bf-11eb-9c0e-696d001d1f80.png)

Hello, (I am new to terraform) i would like to know what is the most recommended target for this deployment?
**Server or Serverless?**

**Comment by ofhouse** [comment]
Hi, the target is set automatically by `tf-next`, so you don't need to define it in the config altogether.
If it is defined, it will be overriden with the correct value.

**Comment by otekdo** [comment]
Ohh ok, thanks!
