### ISSUE TITLE
s3-put bad request error

### ISSUE THREAD

**Issue by otekdo** [dealmore/terraform-aws-next-js#98]
Hi, when i tried to run the command "terraform apply" in my project 
with my windows 10 machine

Everything was ok, until this bug appeared

`Error: Error running command './s3-put -r us-east-1 -T C:/apps/web/mynextapp/client/.next-tf/static-website-files.zip /next-tf-deploy-source20210331135505030700000001/static-website-files.zip': exit status 1. Output: '.' is not recognized as an internal or external command,
operable program or batch file.`

![image](https://user-images.githubusercontent.com/65221868/113157724-28b14800-9209-11eb-9e59-7f09166bf08b.png)
**It created the 3 buckets successfully**

![image](https://user-images.githubusercontent.com/65221868/113157841-3c5cae80-9209-11eb-90a8-2f8a138c661c.png)
**It created both CDN distribution successfully**

![image](https://user-images.githubusercontent.com/65221868/113157975-5ac2aa00-9209-11eb-904a-75ed20a8257d.png)
**And it also created both functions, and other needed resources**

That's the error i got:

`Error: Error running command './s3-put -r us-east-1 -T C:/apps/web/mynextapp/client/.next-tf/static-website-files.zip /next-tf-deploy-source20210331135505030700000001/static-website-files.zip': exit status 1. Output: '.' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by otekdo** [comment]
It does not let me deploy the website, that mistake is still happening!

`module.tf_next.module.statics_deploy.null_resource.static_s3_upload (local-exec): Executing: ["cmd" "/C" "./s3-put -r us-east-1 -T C:/apps/web/mynextapp/client/.next-tf/static-website-files.zip /next-tf-deploy-source20210331135505030700000001/static-website-files.zip"]
module.tf_next.module.statics_deploy.null_resource.static_s3_upload (local-exec): '.' is not recognized as an internal or external command,
module.tf_next.module.statics_deploy.null_resource.static_s3_upload (local-exec): operable program or batch file.`

**Comment by otekdo** [comment]
Well, after a few tries i discovered that i had to upload the .zip file by myself in the specified bucket.
So now my website got deployed!

**Comment by ofhouse** [comment]
Yes Windows is currently not supported since we rely internally on some Bash scripts that are executed during `terraform apply`.
Bash is not supported on Windows and that's the reason why you see those errors.

Windows support is not a top priority for this project. Do you have the possibility to use a Linux-Subsystem (WSL), or a CI (e.g. [Terraform Cloud](https://www.terraform.io/cloud)) for making the deployments?

**Comment by otekdo** [comment]
Thanks for these details, did not know that!
I'll give a try with Terraform Cloud!

**Comment by ofhouse** [comment]
No problem,
every customer-facing route ("all incoming traffic") is served by the CDN (CloudFront).

CloudFront uses two different sources (three with image optimization) where a request is served from.
S3 and API-Gateway + Lambda are sources where CloudFront forwards the incoming traffic to when no copy is in the CloudFront cache.
The request from a viewer itself is terminated by CloudFront, so no customer will request (or see) the S3 or API-Gateway resources directly but they are initiated (and signed for S3 sources) by CloudFront.

**Comment by otekdo** [comment]
Wow, amazing!
Thanks for the deep explanation!

**Comment by LarissaKim** [comment]
Didn't realize Windows wasn't supported until running into this issue while deploying.

> When using this module together with [Terraform Cloud](https://www.terraform.io/) make sure that you also upload the build output from the [tf-next](https://www.npmjs.com/package/tf-next) task.

Could you please clarify this instruction? Where should the `.next-tf` folder content be uploaded on Terraform Cloud?
